# ---------------------------------------
block_step_jump: "on"
# ---------------------------------------
# Stone Slab
block_type_1: "44"
block_type_2: "43"
block_type_3: "157"
# ---------------------------------------
# how heigh player will be on air 
# ---------------------------------------
player_jump_height: "10"